name: Terraform Deploy to S3 for testing remote backend and workspaces and modules
on:
  push:
    branches:
      - develop
      - staging
      - prod

jobs:
  terraform-deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3 # use your version or latest stable

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "BACKEND_CONFIG=backend-develop.tfbackend" >> $GITHUB_ENV
            echo "ENV=develop" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "BACKEND_CONFIG=backend-staging.tfbackend" >> $GITHUB_ENV
            echo "ENV=staging" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
            echo "BACKEND_CONFIG=backend-prod.tfbackend" >> $GITHUB_ENV
            echo "ENV=prod" >> $GITHUB_ENV
          fi

      - name: Terraform Init
        run: terraform init -backend-config=${{ env.BACKEND_CONFIG }}

      - name: Terraform Select Workspace
        run: terraform workspace select ${{ env.ENV }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
